# Generated by Django 3.0.3 on 2020-03-01 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200301_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='reply_to',
        ),
    ]
