export const GET_FOOD_ITEMS = "GET_FOOD_ITEMS";
export const GET_SEARCH_RESULT = "GET_SEARCH_RESULT";
export const GET_FOOD_ITEM = "GET_FOOD_ITEM";
export const GET_CLICKED_ITEM_ID = "GET_CLICKED_ITEM_ID";
export const GET_ERRORS = 'GET_ERRORS';